---
- name: create_domain | configuring samba
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart samba-ad-dc

- name: rm smb.conf
  file:
    state: absent
    path: "/etc/samba/smb.conf"

- name: create_domain | checking if domain created
  stat:
    path: /etc/samba/.samba_ad_created
  register: samba_ad_created_check

- name: provision
  command: >
    samba-tool domain provision
      --server-role=dc
      --dns-backend=SAMBA_INTERNAL
      --realm={{ sambadc_realm|upper }}
      --domain={{ sambadc_realm.split('.')[0]|upper }}
      --adminpass='{{ samadc_admin_password }}'
      --use-rfc2307
  register: samba_ad_created
  when: >
        not samba_ad_created_check['stat']['exists'] and
        not sambadc_join

- name: create_domain | marking domain as created
  file:
    dest: /etc/samba/.samba_ad_created
    state: touch
  when: >
        samba_ad_created
