---
- name: rm smb.conf
  file:
    state: absent
    path: "{{ sambadc_smbconf }}"

- name: provision
  command: >
    samba-tool domain provision
      --server-role=dc
      --dns-backend=SAMBA_INTERNAL
      --realm={{ sambadc_realm|upper }}
      --domain={{ sambadc_realm.split('.')[0]|upper }}
      --adminpass='{{ sambadc_admin_password }}'
      --use-rfc2307
  notify:
    - restart samba-ad-dc
