---
# adapted from https://github.com/mrlesmithjr/ansible-samba/blob/master/tasks/create_domain.yml
- name: create_domain | checking if domain created
  stat:
    path: /var/.samba_ad_created
  register: samba_ad_created_check

- name: rm smb.conf
  file:
    state: absent
    path: "{{ sambadc_smbconf }}"
  when: >
    not samba_ad_created_check['stat']['exists']

- name: provision
  command: >
    samba-tool domain provision
      --server-role=dc
      --dns-backend=SAMBA_INTERNAL
      --realm={{ sambadc_realm|upper }}
      --domain={{ sambadc_realm.split('.')[0]|upper }}
      --adminpass='{{ sambadc_admin_password }}'
      --use-rfc2307
  register: samba_ad_created
  notify:
    - restart samba-ad-dc
  when: >
    not samba_ad_created_check['stat']['exists']

- name: create_domain | marking domain as created
  file:
    dest: /var/.samba_ad_created
    state: touch
  become: true
  register: _samba_domain_created
  when: >
    samba_ad_created['changed'] and
    not samba_ad_created_check['stat']['exists']
