---
- name: rm smb.conf
  file:
    state: absent
    path: "{{ sambadc_smbconf }}"

- name: join_domain | Joining Domain
  command: >
    samba-tool domain join 
    {{ sambadc_realm|upper }} DC 
    --username="{{ sambadc_realm.split('.')[0]|upper  }}\administrator" 
    --password='{{ samadc_admin_password }}'
    --realm={{ sambadc_realm|upper }}
    --dns-backend=SAMBA_INTERNAL 
  notify:
    - restart samba-ad-dc
