---
# adapted from https://github.com/mrlesmithjr/ansible-samba/blob/master/tasks/create_domain.yml
- name: create_domain | checking if domain created
  stat:
    path: /var/.samba_ad_created
  register: samba_ad_created_check

- name: rm smb.conf
  file:
    state: absent
    path: "{{ sambadc_smbconf }}"
  when: not samba_ad_created_check['stat']['exists']

- name: join_domain | Joining Domain
  command: >
    samba-tool domain join 
    {{ sambadc_realm|upper }} DC 
    --username="{{ sambadc_realm.split('.')[0]|upper  }}\administrator" 
    --password='{{ sambadc_admin_password }}'
    --realm={{ sambadc_realm|upper }}
    --dns-backend=SAMBA_INTERNAL 
  register: samba_ad_created
  when: not samba_ad_created_check['stat']['exists']
  notify:
    - restart samba-ad-dc

- name: create_domain | marking domain as created
  file:
    dest: /var/.samba_ad_created
    state: touch
  register: _samba_domain_created
  when: >
    samba_ad_created['changed'] and
    not samba_ad_created_check['stat']['exists']
