---
# adapted from https://github.com/mrlesmithjr/ansible-samba/blob/master/tasks/join_domain.yml
- name: join_domain | Checking If Already Joined To Domain
  stat:
    path: /var/.samba_ad_joined
  register: samba_ad_join_check

- name: rm smb.conf
  file:
    state: absent
    path: "{{ sambadc_smbconf }}"
  when: not samba_ad_join_check['stat']['exists']

- name: join_domain | Joining Domain
  command: >
    samba-tool domain join 
    {{ sambadc_realm|upper }} DC 
    --username="{{ sambadc_realm.split('.')[0]|upper  }}\administrator" 
    --password='{{ sambadc_admin_password }}'
    --realm={{ sambadc_realm|upper }}
    --dns-backend=SAMBA_INTERNAL 
  register: _samba_domain_joined
  when: not samba_ad_join_check['stat']['exists']
  notify:
    - restart samba-ad-dc

- name: join_domain | Marking As Joined To Domain
  file:
    path: /var/.samba_ad_joined
    state: touch
  become: true
  when: _samba_domain_joined['changed']
